const fs = require("fs");
// fs.writeFile(
//   "generated.txt",
//   "This file has been generated with nodejs fs new module",
//   function (error) {
//     if (error) console.log(error);
//     else console.log("File has been created successfuly.");
//   }
// );
// fs.unlink("generated.txt", function (error) {
//   console.log(error);
// });
// fs.writeFileSync(
//   "generate.txt",
//   "This is a file generated by nodejs in synchronyise manner."
// );
// fs.appendFileSync("./learned.txt", "\nHi, I am Subhan");
// const result = fs.readFileSync("./learned.txt", "utf-8");
// console.log(result);
// fs.cpSync("./learned.txt", "./copy.txt");
// fs.mkdir("Folder_1/First/Second", { recursive: true }, function (error) {
//   if (error) console.log(error);
//   else console.log(error);
// });
